# ############################################################################ #
#          .-.                                                                 #
#    __   /   \   __                                                           #
#   (  `'.\   /.'`  )   Pong-Arcade - docker-compose.yaml                      #
#    '-._.(;;;)._.-'                                                           #
#    .-'  ,`"`,  '-.                                                           #
#   (__.-'/   \'-.__)   By: Rosie (https://github.com/BlankRose)               #
#       //\   /         Last Updated: Tuesday, August 15, 2023 3:30 PM         #
#      ||  '-'                                                                 #
# ############################################################################ #

version: '3'

services:

  # Frontend written in React
  frontend:
    container_name: pong-frontend
    image: pong-front:latest
    build: ./frontend
    ports:
      - "${WEB_ACCESS_PORT}:3000"
    environment:
      - REACT_APP_API_PORT=${API_ACCESS_PORT}
      - REACT_APP_API_UID=${API_UID}
    volumes:
      - ./frontend/src:/app/src
      - ./frontend/public:/app/public

  # Backend written in NestJS
  backend:
    container_name: pong-backend
    image: pong-back:latest
    build: ./backend
    ports:
      - "${API_ACCESS_PORT}:3000"
    environment:
      - API_UID=${API_UID}
      - API_SECRET=${API_SECRET}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    networks:
      - pong-data
    volumes:
      - ./backend/app/src:/app/src

  # Database using PostgreSQL
  database:
    container_name: pong-database
    image: postgres:latest
    expose:
      - "5432"
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    networks:
      - pong-data

networks:

  pong-data:
    driver: bridge
